export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const ERROR_REGISTER = 'ERROR_REGISTER'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const LOAD_USER = 'LOAD_USER'
export const FAIL_USER = 'FAIL_USER'


 export const PROFILE_USER = 'PROFILE_USER'
 export const PROFILE_ERROR = 'PROFILE_ERROR' 
 export const CLEAR_PROFILE = 'CLEAR_PROFILE' 
 export const UPDATE_PROFILE = 'UPDATE_PROFILE'
 export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
 export const GET_PROFIELS='GET_PROFIELS'
